// Fills <div id="root"></div> in every route file written by seo.plugin.ts with the server-rendered page,
// so dist/index.html, dist/services/<slug>/index.html etc. contain the real content (H1, text, links).
// Runs after `vite build` (client) and `vite build --ssr src/entry-server.tsx --outDir dist-ssr`.
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const dist = resolve(root, 'dist');
const ssrDir = resolve(root, 'dist-ssr');
const EMPTY_ROOT = '<div id="root"></div>';

const { render, routes } = await import(pathToFileURL(resolve(ssrDir, 'entry-server.js')).href);

const problems = [];

function prerender(file, url) {
  const path = resolve(dist, file);
  if (!existsSync(path)) {
    problems.push(`${url}: ${file} was not generated by seo.plugin.ts`);
    return;
  }
  const html = readFileSync(path, 'utf8');
  if (!html.includes(EMPTY_ROOT)) {
    problems.push(`${url}: ${file} has no empty #root to fill`);
    return;
  }
  const body = render(url);

  const h1Count = (body.match(/<h1[\s>]/g) ?? []).length;
  if (h1Count !== 1) problems.push(`${url}: expected exactly one <h1>, found ${h1Count}`);
  if (/@vite\/client|@react-refresh/.test(html)) problems.push(`${url}: contains dev-server scripts`);

  // Function replacer so "$" sequences in the page HTML are not treated as replacement patterns
  // data-prerendered tells main.tsx which URL this markup belongs to (hydrate only on that URL)
  writeFileSync(path, html.replace(EMPTY_ROOT, () => `<div id="root" data-prerendered="${url}">${body}</div>`));
}

for (const url of routes) {
  prerender(url === '/' ? 'index.html' : `${url.slice(1)}/index.html`, url);
}
// Not-found page served by Nginx (status 404) for any missing URL; main.tsx client-renders it since the URL differs
prerender('404.html', '/__not-found__');

rmSync(ssrDir, { recursive: true, force: true });

if (problems.length) {
  console.error(`\nprerender failed:\n  - ${problems.join('\n  - ')}`);
  process.exit(1);
}
console.log(`prerender: rendered ${routes.length} routes + 404.html into dist/ (each with exactly one <h1>)`);
